### ISSUE TITLE
Difference from PdfViewer

### ISSUE THREAD

**Issue by tmatous** [pvginkel/ChromePdfViewer#2]
Can you document the difference between this project and the PdfViewer project? I'm not sure which one I should be using.

**Comment by pvginkel** [comment]
The difference is that the PdfViewer project project supports both the Chrome PDF library and XPDF and that the ChromePdfViewer project supports only the Chrome PDF library. This does not mean that you need to include both the Chrome and XPDF library; you just include the library that you're going to use. However, the architecture of these libraries does differ and the PdfViewer library is prefered over the ChromePdfViewer one.
