### ISSUE TITLE
Printing without scaling

### ISSUE THREAD

**Issue by tmatous** [pvginkel/ChromePdfViewer#3]
I am unable to make the print function print without scaling. I need to have the output printed at native scale, at the top left of the page. There seems to be options for this in the dll RenderPDFPageToDC function to do exactly what I want (fitToBounds, stretchToBounds, keepAspectRatio, centerInBounds), but none of the options is working for me.

**Comment by pvginkel** [comment]
Printing, specifically with the Chrome library, is non obvious. Currently, printing is forced at A4 and I wasn't able to find a (good way) to make this more generic and depend on the size of a specific page. Do you have the option of sending a pull request?
